#!/bin/bash

echo "Disabling IPv6..."

cat > /etc/sysctl.d/99-disable-ipv6.conf << 'EOF'
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
EOF

sysctl --system >/dev/null 2>&1

echo "IPv6 status:"
cat /proc/sys/net/ipv6/conf/all/disable_ipv6

echo "Done."
